# Generated by Django 5.0 on 2024-04-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bookimage_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
