# Generated by Django 5.0 on 2024-04-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_payment_method_alter_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo/')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logoes',
                'db_table': 'tbl_logo',
                'managed': True,
            },
        ),
    ]
