# Generated by Django 5.0 on 2024-04-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'managed': True, 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'managed': True, 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='bookimage',
            options={'managed': True, 'verbose_name': 'Book Image', 'verbose_name_plural': 'Book Images'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'managed': True, 'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'managed': True, 'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterModelOptions(
            name='mediagallery',
            options={'managed': True, 'verbose_name': 'Media Gallery', 'verbose_name_plural': 'Media Galleries'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True, 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'managed': True, 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'managed': True, 'verbose_name': 'Publisher', 'verbose_name_plural': 'Publishers'},
        ),
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'managed': True, 'verbose_name': 'Transaction History', 'verbose_name_plural': 'Transaction Histories'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'managed': True, 'verbose_name': 'Wish List', 'verbose_name_plural': 'Wish Lists'},
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='author',
            table='tbl_author',
        ),
        migrations.AlterModelTable(
            name='book',
            table='tbl_book',
        ),
        migrations.AlterModelTable(
            name='bookimage',
            table='tbl_book_images',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='tbl_cart_item',
        ),
        migrations.AlterModelTable(
            name='category',
            table='tbl_category',
        ),
        migrations.AlterModelTable(
            name='discount',
            table='tbl_discunt',
        ),
        migrations.AlterModelTable(
            name='order',
            table='tbl_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='tbl_order_item',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='tbl_publisher',
        ),
        migrations.AlterModelTable(
            name='transactionhistory',
            table='tbl_transaction_history',
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table='tbl_wish_list',
        ),
    ]
